
language: cpp

os: linux
dist: trusty
compiler: gcc
services: docker

cache: ccache

env:
  global:
    - DOCKER_OPTS="--rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build"
      CONFIGURE_FLAGS="--enable-error-lines --enable-error-functions --enable-tracing --enable-indexed-coupons --enable-extra-safety-checks --enable-sessions --enable-thread-safe-observer-pattern --enable-intraday"
  jobs:
    #
    - INFO="gcc 5.4 (Boost 1.66)"
      DOCKER_IMAGE=lballabio/quantlib-devenv:xenial
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="gcc 6.3 (Boost 1.66)"
      DOCKER_IMAGE=lballabio/quantlib-devenv:zesty
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="gcc 7.4 (Boost 1.72)"
      DOCKER_IMAGE=lballabio/quantlib-devenv:bionic
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="gcc 8.3 (Boost 1.72)"
      DOCKER_IMAGE=lballabio/quantlib-devenv:cosmic
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="gcc 9.x"
      DOCKER_IMAGE=lballabio/quantlib-devenv:eoan
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="gcc 10.x"
      DOCKER_IMAGE=lballabio/quantlib-devenv:focal
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="Clang 6 (Boost 1.72)"
      DOCKER_IMAGE=lballabio/quantlib-devenv:bionic
      CACHEDCC="ccache clang" CACHEDCXX="ccache clang++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="Clang 7 (Boost 1.72)"
      DOCKER_IMAGE=lballabio/quantlib-devenv:cosmic
      CACHEDCC="ccache clang" CACHEDCXX="ccache clang++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="Clang 8 (Boost 1.72)"
      DOCKER_IMAGE=lballabio/quantlib-devenv:disco
      CACHEDCC="ccache clang" CACHEDCXX="ccache clang++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="Clang 9"
      DOCKER_IMAGE=lballabio/quantlib-devenv:eoan
      CACHEDCC="ccache clang" CACHEDCXX="ccache clang++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="Clang 10"
      DOCKER_IMAGE=lballabio/quantlib-devenv:focal
      CACHEDCC="ccache clang" CACHEDCXX="ccache clang++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror"
    #
    - INFO="C++03 mode"
      DOCKER_IMAGE=lballabio/quantlib-devenv:eoan
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Werror -std=c++03"
    #
    - INFO="C++11 mode"
      DOCKER_IMAGE=lballabio/quantlib-devenv:rolling
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror -std=c++11"
    #
    - INFO="C++14 mode"
      DOCKER_IMAGE=lballabio/quantlib-devenv:rolling
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror -std=c++14"
    #
    - INFO="C++17 mode"
      DOCKER_IMAGE=lballabio/quantlib-devenv:rolling
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      CXXFLAGS="-O2 -g0 -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror -std=c++17"
    #
    - INFO="C++11 classes enabled"
      DOCKER_IMAGE=lballabio/quantlib-devenv:rolling
      CACHEDCC="ccache gcc" CACHEDCXX="ccache g++"
      MORE_CONFIGURE_FLAGS="--enable-std-classes"
      CXXFLAGS="-O2 -g0 -std=c++17 -Wall -Wno-unknown-pragmas -Werror"

before_install:
  - docker pull ${DOCKER_IMAGE}

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./autogen.sh
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./configure --disable-static ${CONFIGURE_FLAGS} ${MORE_CONFIGURE_FLAGS} CC="${CACHEDCC}" CXX="${CACHEDCXX}" CXXFLAGS="${CXXFLAGS}"
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --max-size=2.5G
  # - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} make -j 2 -C ql
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} make -j 2

